### ISSUE TITLE
Get-DbaOperatingSystem throws errors on Windows 2003 and Windows 2008

### ISSUE THREAD

**Issue by sqllensman** [sqlcollaborative/dbatools#3163]
### General Troubleshooting steps

- [ Y] Verified running the latest release of dbatools?
- [Y ] Verified errors are not related to permissions?
- [ Y] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System Windows Server 2016
 - PowerShell Version: V5.1
 - SQL Server (Edition|Version): n/a

## Steps to Reproduce

When Get-DbaOperatingSystem is called against a Windows 2008 or Windows 2003 machine the function fails with message: 
WARNING: [Get-DbaOperatingSystem][22:11:02] Failure collecting PowerPlan information on SBCW21 | An error occurred while enumerating through a collection: Invalid namespace .

This is an expected error as the WMI Class being queried Win32_PowerPlan only exists on Windows 2008R2 or Higher

Rather than command returning an error this should be trapped and Not Available or null should be returned

### Additional information

The function also has a hard dependency on WinRM being available as it directly tries to execute the command : 
$psVersion = Invoke-Command2 -ComputerName $computerResolved -Credential $Credential -ScriptBlock { $PSVersionTable.PSVersion }

Even when WinRM is not available all other required information can usually be obtained as the calls to Get-DbaCmObject are all able to fall back to using DCom and return information.
Again, rather than failing the entire command the Function should return all available information and simply return that Powershell Version could not be determined. 

An alternative could be to look at the Registry Keys on the remote computer to determine the version
eg HKLM\Software\Microsoft\PowerShell\1\PowerShellEngine or
     HKLM\Software\Microsoft\PowerShell\3\PowerShellEngine

**Comment by sqllensman** [comment]
Testing this command further there is also an issue when running against Windows Machines that are running SSRS with an SPN registered. The issue is documented in https://dba.stackexchange.com/questions/129286/how-do-i-enable-both-powershell-remoting-and-spn-for-sql-server-reporting

In cases where it is not possible to do the required fix to register an SPN for remoting it would be nice if the command could simply output a warning when remoting failed and still return the remaining values

**Comment by wsmelton** [comment]
This should be fixed (recall Fred addressed this in one of his magical PRs). If not please reopen a new issue with details and logs.

**Comment by sqllensman** [comment]
Tested on 0.9.472 and all issues are still present. 

I actually have a Pull Request ready to fix / work around the issues.  I will raise a new issue and submit the fix.
