### ISSUE TITLE
Backup-DbaDatabase conversion error

### ISSUE THREAD

**Issue by mokadar** [sqlcollaborative/dbatools#5024]
Hi, Getting following error when running dbaTools powershell script with Invoke-DbaDbLogShipping command. have tested with different environment with the  same result

could you please help :)

## Error

```powershell
<#
WARNING: [14.55.26][Backup-DbaDatabase] Backup Failed | Conversion failed when converting date and/or time from
character string.
WARNING: [14.55.26][Invoke-DbaDbLogShipping] Something went wrong restoring the secondary database | Cannot bind
argument to parameter 'Path' because it is null.
#>
```

**##Current  Script**
```powershell
<#
    $params = @{
SourceSqlInstance = 'LOCALHOST'
DestinationSqlInstance = 'DB002'
Database = 'logShip'
BackupNetworkPath= '\\DB001\LS_Primary'
BackupLocalPath= 'C:\LS_Primary'
BackupScheduleFrequencyType = 'daily'
BackupScheduleFrequencyInterval = 1
CompressBackup = $true
CopyScheduleFrequencyType = 'daily'
CopyScheduleFrequencyInterval = 1
GenerateFullBackup = $true
RestoreScheduleFrequencyType = 'daily'
RestoreScheduleFrequencyInterval = 1
SecondaryDatabaseSuffix = 'DR'
CopyDestinationFolder = '\\DB002\LS_Copy'
Force = $true
 }
Invoke-DbaDbLogShipping @params 
#>
```
## Environmental data

 - PowerShell:  5      1      14393  2248
 - - SQL Server: Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Aug 22 2017 17:04:49   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard Evaluation 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by js0505** [comment]
I received a similar type of conversion issue this morning, attached are my results of running 0..4 | %{$error[$_] | select *}
[Logship_Error.txt](https://github.com/sqlcollaborative/dbatools/files/2817611/Logship_Error.txt)

**Comment by mokadar** [comment]
Hi Sanderstad. Here is the result form the above command. and thanks again for quick response. 

writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Cannot bind argument to parameter 'Path' because it is null. ---> System.Mana
                        gement.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path'
                         because it is null.
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext f
                        uncContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame fra
                        me)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedF
                        rame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedF
                        rame frame)
                           --- End of inner exception stack trace ---
TargetObject          : LOCALHOST
CategoryInfo          : InvalidData: (LOCALHOST:String) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Invoke-DbaDbLogShipping,Stop-Function
ErrorDetails          : Cannot bind argument to parameter 'Path' because it is null.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, <No file>: line 104459
                        at Invoke-DbaDbLogShipping<Process>, <No file>: line 60486
                        at <ScriptBlock>, C:\Script\TestDbLogshipping.ps1: line 19
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

PSMessageDetails      : 
Exception             : System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to param
                        eter 'Path' because it is null.
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext f
                        uncContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame fra
                        me)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedF
                        rame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedF
                        rame frame)
TargetObject          : 
CategoryInfo          : InvalidData: (:) [Restore-DbaDatabase], ParameterBindingValidationException
FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Restore-DbaDatabase
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Invoke-DbaDbLogShipping<Process>, <No file>: line 60429
                        at <ScriptBlock>, C:\Script\TestDbLogshipping.ps1: line 19
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Conversion failed when converting date and/or time from character string. ---
                        > System.Data.SqlClient.SqlException: Conversion failed when converting date and/or time from c
                        haracter string.
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction act
                        ion, Object execObject, DataSet fillDataSet, Boolean catchException)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlComma
                        nd, Boolean retry)
                           --- End of inner exception stack trace ---
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Backup-DbaDatabase,Stop-Function
ErrorDetails          : Conversion failed when converting date and/or time from character string.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, <No file>: line 104459
                        at Backup-DbaDatabase<Process>, <No file>: line 2817
                        at Invoke-DbaDbLogShipping<Process>, <No file>: line 60344
                        at <ScriptBlock>, C:\Script\TestDbLogshipping.ps1: line 19
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

PSMessageDetails      : 
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "ExecuteWithResults" 
                        with "1" argument(s): "An exception occurred while executing a Transact-SQL statement or batch.
                        " ---> Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred w
                        hile executing a Transact-SQL statement or batch. ---> System.Data.SqlClient.SqlException: Conv
                        ersion failed when converting date and/or time from character string.
                           at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction act
                        ion, Object execObject, DataSet fillDataSet, Boolean catchException)
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlComma
                        nd, Boolean retry)
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteWithResults(String sqlComma
                        nd, Boolean retry)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext f
                        uncContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame fra
                        me)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedF
                        rame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedF
                        rame frame)
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                           at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnder
                        bar, Object inputToProcess)
                           at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : ExecutionFailureException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-DbaBackupHistory<Process>, <No file>: line 26671
                        at Backup-DbaDatabase<Process>, <No file>: line 2761
                        at Invoke-DbaDbLogShipping<Process>, <No file>: line 60344
                        at <ScriptBlock>, C:\Script\TestDbLogshipping.ps1: line 19
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PSMessageDetails      : 
Exception             : System.IO.IOException: The process cannot access the file 'C:\Program Files\WindowsPowerShell\M
                        odules\dbatools\0.9.750\bin\dbatools.dll' because it is being used by another process.
                           at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
                           at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite
                        , Boolean checkHost)
                           at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
                           at Microsoft.PowerShell.Commands.FileSystemProvider.CopyFileInfoItem(FileInfo file, String d
                        estinationPath, Boolean force, PowerShell ps)
                           at Microsoft.PowerShell.Commands.FileSystemProvider.CopyItemLocalOrToSession(String path, St
                        ring destinationPath, Boolean recurse, Boolean Force, PowerShell ps)
                           at Microsoft.PowerShell.Commands.FileSystemProvider.CopyItem(String path, String destination
                        Path, Boolean recurse)
                           at System.Management.Automation.SessionStateInternal.CopyItem(CmdletProvider providerInstanc
                        e, String path, String copyPath, Boolean recurse, CmdletProviderContext context)
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Copy-Item], IOException
FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.CopyItemCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 93
                        at Import-ModuleFile, C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.750\dbatools.psm1
                        : line 40
                        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.750\dbatools.psm1: li
                        ne 184
                        at <ScriptBlock>, C:\Script\TestDbLogshipping.ps1: line 19
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

**Comment by Stuart-Moore** [comment]
Thanks, think that's narrowed in down a bit.

I've just pushed a branch https://github.com/sqlcollaborative/dbatools/tree/logshipfix which I think fixes it, or should at least fail with a nicer error message 

@js0505 or @mokadar would you be able to pull it and try it out please

**Comment by mokadar** [comment]
Hi, it's still failing with the attached error message. 
[error07022019.txt](https://github.com/sqlcollaborative/dbatools/files/2842532/error07022019.txt)

**Comment by potatoqualitee** [comment]
should be fixed now! 👍

**Comment by potatoqualitee** [comment]
The fix was included in #5753 which will be released with dbatools 1.0 on Thursday morning 💯

**Comment by mokadar** [comment]
awesome:) Thanks for your great help Chrissy,

man. 17. jun. 2019 kl. 14:09 skrev Chrissy LeMaire <notifications@github.com
