### ISSUE TITLE
[Bug] Issue using module with non-interactive login in SQL Agent job

### ISSUE THREAD

**Issue by m1chael-d** [sqlcollaborative/dbatools#5365]
I have been getting intermittent errors when trying to execute dbatools in a SQL Server Agent job. I have stripped down my larger PS code solution to isolate where i am running into problems.

**SQL job**
**Type:** Operating system (CmdExec)
**Run as:** proxy service account with access to "servername"
**Job Step:** `powershell.exe -ExecutionPolicy Bypass -Command "Import-Module dbatools -force; Get-DbaBuildReference -SqlInstance <servername>;$error[0] | select *;Get-Module dbatools"`

**error:**
```
Exception calling "InvokeScript" with "4" argument(s): "Cannot bind argument 
to parameter 'Path' because it is null."
At C:\Program 
Files\WindowsPowerShell\Modules\dbatools\0.9.803\dbatools.psm1:40 char:9
+         $ExecutionContext.InvokeCommand.InvokeScript($false, ([script ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ParameterBindingValidationException
 
Join-DbaPath : Cannot bind argument to parameter 'Path' because it is an empty 
string.
At C:\Program 
Files\WindowsPowerShell\Modules\dbatools\0.9.803\dbatools.psm1:223 char:77
+ ... .Message.LogHost]::LoggingPath = Join-DbaPath $script:AppData "PowerS ...
+                                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-DbaPath], ParameterBindin 
   gValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAl 
   lowed,Join-DbaPath
 
WARNING: [08:41:41][Get-DbaBuildReference] Error loading SQL build reference | 
Cannot bind argument to parameter 'Path' because it is null.
```

**$error[0]**
```
writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: Cannot bind argument to parameter 
                        'Path' because it is null. ---> System.Management.Autom
                        ation.ParameterBindingValidationException: Cannot bind 
                        argument to parameter 'Path' because it is null.
                           at System.Management.Automation.ExceptionHandlingOps
                        .CheckActionPreference(FunctionContext funcContext, 
                        Exception exception)
                           at System.Management.Automation.Interpreter.ActionCa
                        llInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTry
                        CatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTry
                        CatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.Interpre
                        ter.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.LightLam
                        bda.RunVoid1[T0](T0 arg0)
                           at System.Management.Automation.PSScriptCmdlet.RunCl
                        ause(Action`1 clause, Object dollarUnderbar, Object 
                        inputToProcess)
                           at System.Management.Automation.PSScriptCmdlet.DoEnd
                        Processing()
                           at System.Management.Automation.CommandProcessorBase
                        .Complete()
                           --- End of inner exception stack trace ---
TargetObject          : 
CategoryInfo          : InvalidData: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Get-DbaBuildReference,Stop-Function
ErrorDetails          : Cannot bind argument to parameter 'Path' because it is 
                        null.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Mo
                        dules\dbatools\0.9.803\allcommands.ps1: line 109058
                        at Get-DbaBuildReference<Begin>, C:\Program Files\Windo
                        wsPowerShell\Modules\dbatools\0.9.803\allcommands.ps1: 
                        line 28408
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

**Get-Module dbatools**
```
Name              : dbatools
Path              : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.803
                    \dbatools.psm1
Description       : The community module that enables SQL Server Pros to 
                    automate database development and server administration
Guid              : 9d139310-ce45-41ce-8e8b-d76335aa1789
Version           : 0.9.803
ModuleBase        : C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.803
ModuleType        : Script
PrivateData       : {PSData}
AccessMode        : ReadWrite
ExportedAliases   : {}
ExportedCmdlets   : {[Select-DbaObject, Select-DbaObject], 
                    [Set-DbatoolsConfig, Set-DbatoolsConfig]}
ExportedFunctions : {[Add-DbaAgDatabase, Add-DbaAgDatabase], 
                    [Add-DbaAgListener, Add-DbaAgListener], [Add-DbaAgReplica, 
                    Add-DbaAgReplica], [Add-DbaCmsRegServer, 
                    Add-DbaCmsRegServer]...}
ExportedVariables : {}
NestedModules     : {}
```

**Comment by m1chael-d** [comment]
This SQL Server Job will execute without error if there is a proxy service account session on the SQL Server. This can be a RDP session or a 'runas' "program" session.

**Comment by m1chael-d** [comment]
even just the following get an error
`powershell.exe -ExecutionPolicy Bypass -Command "Import-Module dbatools -force;"`

`Exception calling "InvokeScript" with "4" argument(s): "Cannot bind argument 
to parameter 'Path' because it is null."
At C:\Program 
Files\WindowsPowerShell\Modules\dbatools\0.9.803\dbatools.psm1:40 char:9
+         $ExecutionContext.InvokeCommand.InvokeScript($false, ([script ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ParameterBindingValidationException
 
Join-DbaPath : Cannot bind argument to parameter 'Path' because it is an empty 
string.
At C:\Program 
Files\WindowsPowerShell\Modules\dbatools\0.9.803\dbatools.psm1:223 char:77
+ ... .Message.LogHost]::LoggingPath = Join-DbaPath $script:AppData "PowerS ...
+                                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-DbaPath], ParameterBindin 
   gValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAl 
   lowed,Join-DbaPath`

**Comment by potatoqualitee** [comment]
Please update to the latest version - this issue has been addressed.

**Comment by m1chael-d** [comment]
still having the issue after upgrading:
`Exception calling "InvokeScript" with "4" argument(s): "Cannot bind argument 
to parameter 'Path' because it is null."
At C:\Program 
Files\WindowsPowerShell\Modules\dbatools\0.9.819\dbatools.psm1:40 char:9
+         $ExecutionContext.InvokeCommand.InvokeScript($false, ([script ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ParameterBindingValidationException
 
Join-DbaPath : Cannot bind argument to parameter 'Path' because it is an empty 
string.
At C:\Program 
Files\WindowsPowerShell\Modules\dbatools\0.9.819\dbatools.psm1:223 char:77
+ ... .Message.LogHost]::LoggingPath = Join-DbaPath $script:AppData "PowerS ...
+                                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-DbaPath], ParameterBindin 
   gValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAl 
   lowed,Join-DbaPath`

**Comment by potatoqualitee** [comment]
this is going to be a challenge, i think it's limited by agent and intermittent 😫😭 @SQLDBAWithABeard any idea what it could be? is this common? here's where script:appdata can be found

![image](https://user-images.githubusercontent.com/8278033/57094141-16be8600-6d10-11e9-838c-dc339af05363.png)

**Comment by m1chael-d** [comment]
it works fine if the the windows account used as the proxy account has a session on the server but if there is no session the sql job fails.

**Comment by m1chael-d** [comment]
this works with no error;
1. `New-PSSession -ComputerName <servername>`
![image](https://user-images.githubusercontent.com/32747976/57097031-7c3c5380-6ccb-11e9-9851-6a384ec531ff.png)
2. execute sql job
`powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Import-Module dbatools;Get-Module dbatools"`

Results:
![image](https://user-images.githubusercontent.com/32747976/57097278-3764ec80-6ccc-11e9-8b9a-8e2be3ef6064.png)

**Comment by SQLDBAWithABeard** [comment]
Yikes, this looks gnarly. I will take a look over the weekend.  Can I get some OS details and PS Version details for the instance please @m1chael-d

**Comment by m1chael-d** [comment]
let me know what else you need

![image](https://user-images.githubusercontent.com/32747976/57111909-bb31cf80-6cf2-11e9-8e31-b0408c3871c2.png)

![image](https://user-images.githubusercontent.com/32747976/57111966-ee745e80-6cf2-11e9-871a-4ef3537bfe38.png)

![image](https://user-images.githubusercontent.com/32747976/57112005-14016800-6cf3-11e9-9f67-04eaf0d64b19.png)

**Comment by JoDouglass** [comment]
I _think_ this is actually a pretty easy fix, but I know very, very little about configuration.ps1, so I don't want to submit this as an edit without checking...

I consistently get this error if I'm using a non-interactive account as a proxy in the SQL Server Agent to run any PoSh script. It doesn't seem to cause any problems, but it gunks up the agent history and has confused my colleagues a few times (it's a red herring when you have an actual problem you're looking into).

In configuration.ps1, there are two sections which try to set the local and roaming app data directories. On my non-interactive proxies, via agent, $Env:LocalAppData and $Env:AppData are always null when this runs - and the way the script is written, it always tries to use those environment variables, and if that fails, then it tries to use [Environment]::GetFolderPath("LocalApplicationData") and [Environment]::GetFolderPath("ApplicationData") instead.

With apologies to Fred (as per the comments at the top of configuration.ps1), I edited my version of the file so that it checks whether those two environment variables are nothing first, and only uses them if it can - and tada, no error.

Is there a particular reason it always tries to use $Env:LocalAppData and $Env:AppData first, rather than making sure they're not null before using them? If not, then I'll happily submit my fix as a change, if no one beats me to it.

**Comment by wsmelton** [comment]
It won't be something we can skip using if the variables don't return anything. The paths are required for persisting some data we use and the DLL is also written to the profile of the account using the module.

It will take a bit more than just checking if they have a path before using them, we have to replace them with something else.

**Comment by JoDouglass** [comment]
It's already doing that - it just does it in the wrong order, I think. Currently it does this:
Try standard method > fail > check if null > use alternative

I'm suggesting this:
Check if null > use alternative

Either way, if $Env:LocalAppData and $EnvAppData are not null, they will be used. And if they are null, [Environment]::GetFolderPath("LocalApplicationData") and [Environment]::GetFolderPath("ApplicationData") will be used. It just cuts out trying and failing.

**Comment by wsmelton** [comment]
Steps to reproduce on local dev machine, which don't think we would be able to duplicate this in Appveyor (or even Actions):

1. Create Windows Login
2. Open `gpedit.msc` 
3. Add login to following: `Computer Configuration > Windows Settings > Security Settings > Local Policies > User Rights Assignment > Deny log on locally`
4. Create Credential for this login in SQL Server:

```sql
USE [master]
GO
CREATE CREDENTIAL [NonInteractiveUser] WITH IDENTITY = N'MELTON-7GJRMQ2\NonInteractiveUser', SECRET = N'P@ssword12345'
GO
```
5. Create SQL Agent Proxy for CmdExec subsystem
```sql
USE [msdb]
GO
EXEC msdb.dbo.sp_add_proxy @proxy_name=N'NonInteractive User',@credential_name=N'NonInteractiveUser', 
		@enabled=1
GO
EXEC msdb.dbo.sp_grant_proxy_to_subsystem @proxy_name=N'NonInteractive User', @subsystem_id=3
GO
```
6. Create basic job that just runs Import and logs step history
```sql
USE [msdb]
GO
DECLARE @jobId BINARY(16)
EXEC  msdb.dbo.sp_add_job @job_name=N'dbatools - NonInteractive', 
		@enabled=1, 
		@notify_level_eventlog=0, 
		@notify_level_email=2, 
		@notify_level_page=2, 
		@delete_level=0, 
		@category_name=N'[Uncategorized (Local)]', 
		@owner_login_name=N'sa', @job_id = @jobId OUTPUT
select @jobId
GO
EXEC msdb.dbo.sp_add_jobserver @job_name=N'dbatools - NonInteractive', @server_name = N'MELTON-7GJRMQ2\SQL17'
GO
USE [msdb]
GO
EXEC msdb.dbo.sp_add_jobstep @job_name=N'dbatools - NonInteractive', @step_name=N'Test Import', 
		@step_id=1, 
		@cmdexec_success_code=0, 
		@on_success_action=1, 
		@on_fail_action=2, 
		@retry_attempts=0, 
		@retry_interval=0, 
		@os_run_priority=0, @subsystem=N'CmdExec', 
		@command=N'powershell.exe -ExecutionPolicy Bypass -Command "$ErrorActionPreference = ''Stop'';Import-Module dbatools -force;"', 
		@database_name=N'master', 
		@flags=32, 
		@proxy_name=N'NonInteractive User'
GO
USE [msdb]
GO
EXEC msdb.dbo.sp_update_job @job_name=N'dbatools - NonInteractive', 
		@enabled=1, 
		@start_step_id=1, 
		@notify_level_eventlog=0, 
		@notify_level_email=2, 
		@notify_level_page=2, 
		@delete_level=0, 
		@description=N'', 
		@category_name=N'[Uncategorized (Local)]', 
		@owner_login_name=N'sa', 
		@notify_email_operator_name=N'', 
		@notify_page_operator_name=N''
GO
```

Run the job and you will see duplicated error:
![image](https://user-images.githubusercontent.com/11204251/64135110-cc770f80-cdaa-11e9-9ebd-1804a9a1d1e2.png)

**Comment by wsmelton** [comment]
@JoDouglass in a non-interactive login `$env:LOCALAPPDATA` and `[Environment]::GetFolderPath("LocalApplicationData")` are both going to be null. Those are profile specific paths. A non-interactive login means it is denied local login and hence neither of those paths are going to exists.

Further testing. The issue this causes is a non-interactive login, one denied local access, literally means it is denied local access to the server/machine. You will not be able to access the local file system with this login. Our module depends on having local access to some path, whether it be profile based or the system temp folder.

If you use that same proxy I provided above in test, you will get an error just doing `dir %temp%` because it cannot access the file system.

@potatoqualitee We will likely need to just work out a post that explains our module depends on having access with the file system. As-is, we cannot operate without having access to the file system.

**Comment by JoDouglass** [comment]
Oh, weird - I tested yesterday and [Environment]::GetFolderPath("LocalApplicationData") and [Environment]::GetFolderPath("ApplicationData") both worked - they pointed to C:\Users\Default\AppData.

I'll double check and make sure no one's fiddled the account I was testing with, it was non-interactive but maybe someone has changed it.

**Comment by wsmelton** [comment]
We definitely do not want to use `C:\Users\Default`. That is a template for any new user profile on a given machine. Anything you put in there will end up in every profile on the machine.

**Comment by JoDouglass** [comment]
Ouch, I did not know that, thanks for the heads up. Think I need to have a chat about how we're setting up service accounts here.

The other issue I have at the moment is that the account I was initially trying to use isn't an Administrator, and not being able to write into C:\Windows\Temp is breaking some functions. I've given the account read/write permissions to that folder, and the script now works.

Is there any information around about what file system access is needed, or is it a case of presuming any accounts running dbatools functions will need to be interactive and in the local administrators group, and then set scripts to run as admin if they fall over?

**Comment by firthro** [comment]
Watching this thread with interest as we have similar errors. We're scheduling a SQL Job using a proxy account executing a command that invokes Powershell  and the Get-DbaUserPermission function. Something like

"powershell.exe -ExecutionPolicy Bypass -NoProfile xyz\Get-DbaUserPermission.ps1

Seems the current advice in the thread is to join the proxy account to the local administrators group.

Our the sql job errors are
Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.25\internal\configurations\configuration.ps1:72 char:44
+     $script:path_FileUserLocal = Join-Path $Env:LocalAppData "$psVers ...
+                                            ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed, Microsoft.PowerShell.Commands.JoinPathCommand
 
Join-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.25\internal\configurations\configuration.ps1:73 char:83
+ ... = Join-Path ([Environment]::GetFolderPath("LocalApplicationData")) "$ ...
etc...

**Comment by potatoqualitee** [comment]
Goodness. @FriedrichWeinmann is there any insight you can provide? this is so strange and the 3rd complaint we've received.

**Comment by wsmelton** [comment]
Well, it is not strange but more by design with how access and non-profile accounts work in Windows.

Local Administrator account is not required, and defeats the security of using a non-interactive login (your security officer will raise issue with this once it is caught).

A non-interactive login as Windows Administrators define it will be: A login that does not require local access to the machine and is added to the security configuration for [Deny log on locally](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/deny-log-on-locally). Out of the box a login in that group will not have access to any part of the file system. (My steps to reproduce above show this issue.)

I see nothing really to fix with this because it will require revamping our messaging and logging system. Particularly the area where we write to files anywhere in the module (default settings we have for profile-based paths).

**Comment by potatoqualitee** [comment]
I recall looking at the code, tho, and it had a "if this is null then use this" and it never used that second this. it was the code that didnt make sense to me.

**Comment by potatoqualitee** [comment]
ohh i see tho, that you have a repro. i shall repro when my brain works again.

**Comment by wsmelton** [comment]
We depend solely on the AppData path being available and that is all we check for in the "if this is null then use this". We either check for `$env:LOCALAPPDATA` or `[Environment]::GetFolderPath("LocalApplicationData")` ...these are both dependent upon profiles.

**Comment by potatoqualitee** [comment]
omg that is an easy fix. where else shall we put it? C:\windows\temp?

**Comment by wsmelton** [comment]
Temp directory won't be accessible to all users. This was discussed above as well.

**Comment by wsmelton** [comment]
The fix to me is basically come out with a mode that turns off anything we do in base module import that has to write to disk.

The logging system is primarily what the paths are for in that configuration script that is getting caught in this setup.

**Comment by HanShi00** [comment]
As a workaround I set the environment variables to the script folder itself, before impoting the DBATOOLS module. This only works if the calling non-interactive account has read/write access to that script folder.

if ($env:LOCALAPPDATA -eq $null -and $env:APPDATA -eq $null){
    # create the varables and set to the script location (need read/write access)
    $env:LOCALAPPDATA = $(Split-Path -parent $PSCommandPath)
    $env:APPDATA = $(Split-Path -parent $PSCommandPath)
}
Import-Module dbatools

**Comment by ColinCampbellCCL** [comment]
I have run into this problem as well; running a SQL Agent job through a proxy.

The folders for $env:LOCALAPPDATA and $env:APPDATA exist, since the account is a normal user account that has logged in interactively on the server. However those variables are null when the SQL Agent job runs.

Also, the variable $psVersionName is incorrect. I'm running PS 5.1 on WS2016, and the folder name is "PowerShell" as per v6+.

**Comment by wsmelton** [comment]
If you are running PS 5.1 how is the PSVersionName variable we use incorrect?

**Comment by ColinCampbellCCL** [comment]
The folder is "PowerShell" as per v6+. The code defaults to "WindowsPowerShell" and changes it to "PowerShell" only for v6+.

configuration.ps1 lines 57-58:
`$psVersionName = "WindowsPowerShell"`
`if ($PSVersionTable.PSVersion.Major -ge 6) { $psVersionName = "PowerShell" }
`
Also, the PowerShell folder is only present in the $env:APPDATA folder, not $env:LOCALAPPDATA. I'm not sure what creates that PowerShell folder. I checked a PSv3 and PSv4 on other computers and the folder doesn't exist.

I tried googling for what causes these environment variables to be null, and came up with nothing. :(

**Comment by wsmelton** [comment]
We create the PowerShell folder under the app data folder. And it appears it has been modified how we create it now, so it always and only creates as PowerShell instead of adjusting based on version....which in this matter it really makes no difference because it is not dependent upon version.

**Comment by ColinCampbellCCL** [comment]
There is still an issue though, since it creates one thing (PowerShell) and then looks for another (WindowsPowerShell). Possibly the version-less name is not fully propagated through the project?

**Comment by wsmelton** [comment]
It has not been addressed yet, so yes it will still exists.

**Comment by potatoqualitee** [comment]
I believe this has been addressed in `1.0.74`. We also introduced `Get-DbatoolsPath` and `Set-DbatoolsPath` tho it should work out of the box. Please let me know if this does not suit your needs (it worked for me after I was able to repro a failure) and I'll reopen the issue.

**Comment by ColinCampbellCCL** [comment]
I'm not sure this has fixed my issue, as the configuration.ps1 file hasn't changed. It still sets the $psVersionName variable to different things based on the PowerShell version.

**Comment by wsmelton** [comment]
@potatoqualitee the paths is not the problem for this one it is the path we are using to copy files and how that `$psversionname` is being used.

**Comment by ColinCampbellCCL** [comment]
The issue does appear to be fixed. I'm running track-logins against a handful of servers, and it was reporting the path issue every run although the script was actually doing the work it should. 

I've uninstalled dbatools v1.0.64, and then installed v1.0.74, and that error has gone away. The job now executes cleanly.

**Comment by potatoqualitee** [comment]
sweet! I have no comment on the psversionname cuz I'm not sure why it's there but thank you both for your feedback - super happy this has been resolved. Thank you @FriedrichWeinmann for the new commands and direction 🏆

**Comment by firthro** [comment]
Many thanks.
