### ISSUE TITLE
[Bug] Test-DBAConnection ignoring -SQLCredential

### ISSUE THREAD

**Issue by dsolodow** [sqlcollaborative/dbatools#6157]
#### PowerShell version:

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.18362.145                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.18362.145                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

#### dbatools Module version:

Name    : dbatools
Path    : C:\Users\dsolodow\OneDrive - Gaylor Electric, 
          Inc\Documents\WindowsPowerShell\Modules\dbatools\1.0.61\dbatools.psd1
Version : 1.0.61

Name    : dbatools
Path    : C:\Users\dsolodow\OneDrive - Gaylor Electric, 
          Inc\Documents\WindowsPowerShell\Modules\dbatools\1.0.46\dbatools.psd1
Version : 1.0.46

#### SQL Server: 

```sql

Column1                                                                                                                                                                 
-------                                                                                                                                                                 
Microsoft SQL Server 2017 (RTM-CU17) (KB4515579) - 14.0.3238.1 (X64) ...                                                                                                
```

#### Host used

- [X] powershell.exe
- [ ] ISE
- [X] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received

```
PSMessageDetails      : 
Exception             : System.Exception: Login failed for user 'GAYLOR\dsolodow'. ---> System.Data.SqlClient.SqlException: Login failed for user 'GAYLOR\dsolodow'.
                           at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, 
                        SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, 
                        SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean 
                        applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
                           at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object 
                        poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions 
                        options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal 
                        oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, 
                        DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean 
                        allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions 
                        userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, 
                        DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory 
                        connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.Open()
                           at CallSite.Target(Closure , CallSite , Object )
                           --- End of inner exception stack trace ---
TargetObject          : TCP:sqlserver\Instance
CategoryInfo          : ConnectionError: (TCP:sqlserver\Instance:String) [], Exception
FullyQualifiedErrorId : dbatools_Get-DbaTcpPort
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Users\dsolodow\OneDrive - Gaylor Electric, Inc\Documents\WindowsPowerShell\Modules\dbatools\1.0.61\allcommands.ps1: line 
                        81747
                        at Get-DbaTcpPort<Process>, C:\Users\dsolodow\OneDrive - Gaylor Electric, 
                        Inc\Documents\WindowsPowerShell\Modules\dbatools\1.0.61\allcommands.ps1: line 34806
                        at Test-DbaConnection<Process>, C:\Users\dsolodow\OneDrive - Gaylor Electric, 
                        Inc\Documents\WindowsPowerShell\Modules\dbatools\1.0.61\allcommands.ps1: line 68319
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```

#### Steps to Reproduce

$admin = get-credential
Test-DbaConnection -SqlInstance sqlserver\instance -SqlCredential $admin

#### Expected Behavior

Successful connection test

#### Actual Behavior

TcpPort reported "Login failed for user" and gave domain\username of the running user rather than the username in $admin
If I launched a PowerShell console as the user for $admin, the test-dbaconnection worked as expected.
Oddly, this worked fine:

```powershell
Invoke-dbaquery -sqlinstance sqlserver\instance -SqlCredential $admin -query "select @@version"
```

**Comment by wsmelton** [comment]
You have to provide Credential parameter for it to use another login for the windows connection. It will not use the sqlcred

**Comment by dsolodow** [comment]
Already tried that with the same result.

**Comment by wsmelton** [comment]
I am not sure what we can do because we already fixed this issue and test passed...

https://github.com/sqlcollaborative/dbatools/blob/e9cefc46343fe220f3129eeee5c9420c0bacd641/functions/Test-DbaConnection.ps1#L109

#5929

**Comment by dsolodow** [comment]
Looking at Test-DBAConnection.ps1 it looks like the port number comes from this line:
```powershell
$tcpport = (Get-DbaTcpPort -SqlInstance $server -Credential $Credential -EnableException).Port
```
Running that by itself throws an error. 
However, if I change that line to:
```powershell
$tcpport = (Get-DbaTcpPort -SqlInstance $server -SqlCredential $Credential -EnableException).Port
```
it returns what I'd expect.

**Comment by dsolodow** [comment]
Confirmed to still occur with dbatools 1.0.77
OS and version: Windows 10 1909
**Steps to Reproduce**
$admin = get-credential
Test-DbaConnection -SqlInstance sqlserver\instance -SqlCredential $admin

**Comment by andreasjordan** [comment]
Solution is to send both credentials to Get-DbaTcpPort, so line will be:
```
$tcpport = (Get-DbaTcpPort -SqlInstance $server -SqlCredential $SqlCredential -Credential $Credential -EnableException).Port
```
Will work on this after #7334 is merged.
