### ISSUE TITLE
[Bug] dbatools creates constant 4100 errors in Windows Event Viewer once loaded in a PS session

### ISSUE THREAD

**Issue by peedeeboy** [sqlcollaborative/dbatools#6543]
### Environmental information

```powershell
#### PowerShell version:
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.18362.752                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.18362.752                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

#### dbatools Module version:
Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.109\dbatools.psd1
Version : 1.0.109
```

```powershell
LCID             Name             DisplayName
----             ----             -----------
2057             en-GB            English (United Kingdom)
```

#### SQL Server:

```sql
Microsoft SQL Server 2017 (RTM-CU17) (KB4515579) - 14.0.3238.1 (X64)   Sep 13 2019 15:49:57   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) 
```

### Report
Once `dbatools` module is loaded in a PowerShell session, there are constant `4100` errors logged to the Windows PowerShell error log, even when the session is idle.  Eventually, the PowerShell session will crash.   
It appears `dbatools` has a background process that gets stuck in a loop throwing errors.
![dbatools_eventviewer_errors](https://user-images.githubusercontent.com/44434629/82325502-43087b80-99d3-11ea-8552-f21e53d11102.PNG)

#### Host used

- [X] powershell.exe
- [X] ISE
- [  ] VS Code
- [  ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [X] Still buggy in powershell.exe

#### Errors Received

From Event Viewer
```xml
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-PowerShell" Guid="{a0c1853b-5c40-4b15-8766-3cf1c58f985a}" /> 
  <EventID>4100</EventID> 
  <Version>1</Version> 
  <Level>3</Level> 
  <Task>106</Task> 
  <Opcode>19</Opcode> 
  <Keywords>0x0</Keywords> 
  <TimeCreated SystemTime="2020-05-19T12:08:30.196628900Z" /> 
  <EventRecordID>24789</EventRecordID> 
  <Correlation ActivityID="{b5436c69-2b90-0004-498e-57b5902bd601}" /> 
  <Execution ProcessID="21320" ThreadID="4356" /> 
  <Channel>Microsoft-Windows-PowerShell/Operational</Channel> 
  <Computer>REDACTED</Computer> 
  <Security UserID="REDACTED" /> 
  </System>
- <EventData>
  <Data Name="ContextInfo">Severity = Warning Host Name = Default Host Host Version = 5.1.18362.752 Host ID = 16351de2-1178-46ff-b122-35e06e012052 Host Application = C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe Engine Version = 5.1.18362.752 Runspace ID = 0bb1118f-ef8c-4d2e-ad8e-4d69a9dc376c Pipeline ID = 1 Command Name = Command Type = Script Name = Command Path = Sequence Number = 92 User = SPEKTRIX\petew Connected User = Shell ID = Microsoft.PowerShell</Data> 
  <Data Name="UserData" /> 
  <Data Name="Payload">Error Message = System error.</Data> 
  </EventData>
  </Event>
```

#### Steps to Reproduce
1. Open a new PowerShell.exe session
2. Check Event Viewer -> Applications and Services Log -> Windows -> Powershell -> Operational. No errors are being logged
3. Run a benign command to make PowerShell session load `dbatools` module, e.g.
```
Get-DbaTempDbUsage -SqlInstance .
```
4. Go back and check Event Viewer -> Applications and Services Log -> Windows -> Powershell -> Operational. After the `4104` events of `dbatools` loaded, the log will be spammed every few seconds with `4100` messages.

#### Expected Behavior
To see `4104` messages in Event Viewer whilst `dbatools` module is loading then noth

#### Actual Behavior
The Event View log is spammed every few seconds with `4100` warnings about script execution failing.  This will continue until the PowerShell session is killed.  
In ISE, closing ISE can leave a zombie process behind, still spamming these errors, which needs to be killed via Task Manager.   
   
Eventually, the PowerShell session will crash if left open long enough.

Tested on multiple Win10 / Server2012 machines at work, and a Win10 machine at home.  Reproducible in all cases.

**Comment by wsmelton** [comment]
If the PowerShell session is crashing then we need the crash dump log from your system in order to fully understand what is causing it to crash, and if that is indeed our module. I have systems where I leave the PowerShell session open for days with our module (among many others) open and I've never had it crash (both desktop and server systems). I as well get the 4100 warning because logging has been turned up on my work system to log that specific message. I can estimate you are seeing those more frequently on your systems because of policies in place, my lab systems that have no AV or Windows Defender rules configured show one 4100 warning on import and then none after that I can see in limited testing.

Our module does utilize multiple runspaces in the background for logging, TEPP and doing some maintenance things (cleaning up log files, etc.). You will find 3 specific runspaces created upon import:

![image](https://user-images.githubusercontent.com/11204251/82326710-e3927780-99a2-11ea-9813-9b6d17395592.png)

You can remove some of these runspaces by controlling the configuration of our module with `Get-DbatoolsConfig` and `Set-DbatoolsConfig`. There are additional options you can do by creating registry keys (output of the Get command should provide these) for it to take effect system wide.

Example, disabling TEPP will remove the runspace for `dbatools-teppasyncache`:

![image](https://user-images.githubusercontent.com/11204251/82327347-dfb32500-99a3-11ea-8b79-ab986086ec58.png)

**Comment by wsmelton** [comment]
In additional you can associate the 4100 warnings and verify if they are for the runspaces our module is creating using this code...

```powershell
$runspaces = Get-Runspace -Name dbatools*
$events = 
foreach ($run in $runspaces) {
    Get-WinEvent -FilterHashtable @{ LogName='Microsoft-Windows-PowerShell/Operational'; Id='4100'} | where Message -match $run.InstanceId
}
$events.Count
```

My home system (work computer) for a current session only has 37 events, and I've had that session running for about 30 minutes or so.

**Comment by peedeeboy** [comment]
@wsmelton Firstly, thank you for your speedy reply!  Secondly, thank you for this awesome PS module!

Running:
```powershell
$runspaces = Get-Runspace -Name dbatools*
$events = 
foreach ($run in $runspaces) {
    Get-WinEvent -FilterHashtable @{ LogName='Microsoft-Windows-PowerShell/Operational'; Id='4100'} | where Message -match $run.InstanceId
}
$events.Count
```
after dbatools is loaded in a fresh PS session, then yes - the count goes up each execution of the above, so it does appear to be dbatools causing them?:
![dbatools_4100_count](https://user-images.githubusercontent.com/44434629/82331100-91217d00-99db-11ea-9776-417dffd43fc0.png)

We had a look at an idle PS session in which dbatools had been previously used, and noticed the `C:\Users\[username]\AppData\Roaming\PowerShell\dbatools` directly being polled constantly.  I assume from your above post that this is something happening in the  `dbatools-logging` runspace, as that is where dbatools logs to?

![dbtools_processmonitor_redacted](https://user-images.githubusercontent.com/44434629/82330508-da250180-99da-11ea-9962-7d5bc0c4a19a.png)

Is this normal behavior for an idle PS sessions that has dbatools loaded to be doing this?  This seems to be a similar frequency to the 4100 errors in Event Viewer, so I wonder if this is the cause of them?

When our PS sessions show the error pop-up, whatever is running in the foreground will continue to run quite happily until the error is dismissed, at which point PS will close. This made us look at background processes.

The only additional runspaces those sessions have are those created by dbatools - that's how we started looking at dbatools as a potential cause of the issue.  We have also only ever seen this in PS sessions where dbatools has been used, I appreciate this is somewhat circumstantial, but thought it worth reporting. 

The most recent error I received was this, related to AAD auth.  This appeared when closing an ISE session in which dbatools had been used:
```
Problem Event Name:	PowerShell
  NameOfExe:	powershell_ise.exe
  FileVersionOfSystemManagementAutomation:	10.0.14409.1018
  InnermostExceptionType:	tiveDirectory.AdalSilentTokenAcquisition
  OutermostExceptionType:	n.Authentication.AadAuthenticationFailed
  DeepestPowerShellFrame:	unknown
  DeepestFrame:	mmon.Authentication.UserTokenProvider.AcquireToken
  ThreadName:	unknown
  OS Version:	6.3.9600.2.0.0.16.7
  Locale ID:	2057

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

```

**Comment by peedeeboy** [comment]
Same PS session just two minutes later, and that count is > 100:
![dbatools_4100_count_2mins](https://user-images.githubusercontent.com/44434629/82332013-c7abc780-99dc-11ea-9ab5-8889757b3cbe.png)

**Comment by wsmelton** [comment]
Yes the logging mechanism will constantly poll that file in order to write logging for our module. If it is failing to do that then it sounds like something in your environment is blocking it as that should not fail or cause the 4100 warnings. (I'm not sure we will be able to fully troubleshoot that one.)

The ISE message you posted is not coming from our module. We cache connection but will not go through them and attempt reconnections without some action being taken by a user (e.g. via command call). The ISE is an extremely chatty piece of software because of the command explorer and just how it works in general....why I don't advise using it, even if you don't have VS Code available.

The message you posted on the error reported from ISE is regarding some software you have on that system using dotnet, that is very unlikely to be our module. The library we have is supported in dotnet but will not perform AD authentication on it's own, a user has to initiate that activity.

**Comment by peedeeboy** [comment]
Thanks for your feedback 👍  Much appreciated!

The weird thing about the 4100s is I get them on personal Win10 boxes, outside of our corporate network.  Also, dbatools successfully writes to its logs when it needs to. 🤷‍♂️ 

So my current feeling is that there is something bugged in dbatools, probably in the logging (causing the 4100s), but this probably isn't the cause of the PowerShell errors we get on long running sessions.

I think for now, I'll look into globally disabling dbatools logging via the Registry, as you suggest.  If we continue getting pop-up errors on long running PS sessions after that, I think we can exclude dbatools from our investigations 👍 

If we dig up anything else useful related to dbatools / 4100s, I'll post back...

**Comment by peedeeboy** [comment]
I think I got to the bottom of what is causing the 4100s in event viewer.  I believe it is lines 83-86 of `logfilescript.ps1`:
```powershell
try { [int]$num_Error = (Get-ChildItem -Path $root.FullName -Filter "dbatools_$($pid)_error_*.xml" | Sort-Object LastWriteTime -Descending | Select-Object -First 1 -ExpandProperty Name | Select-String -Pattern "(\d+)" -AllMatches).Matches[1].Value }
            catch { }
            try { [int]$num_Message = (Get-ChildItem -Path $root.FullName -Filter "dbatools_$($pid)_message_*.log" | Sort-Object LastWriteTime -Descending | Select-Object -First 1 -ExpandProperty Name | Select-String -Pattern "(\d+)" -AllMatches).Matches[1].Value }
            catch { }
```  

Using `Debug-Runspace` I was able to catch the following exception, thrown by line 83:
```powershell
Cannot index into a null array.
At line:83 char:93
+ ...  (Get-ChildItem -Path $root.FullName -Filter "dbatools_$($pid)_error_ ...
+                                                              ~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
```
Line 85 will throw a similar exception.  The `catch { }` blocks are just throwing the exception away, so the script continues, but I think the fact the exception is throw at all causes a 4100 in the Event Viewer every time this loop executes.

To check this theory, I tried an experiment commenting out 83-86, and the steam of 4100s stopped.

**Comment by wsmelton** [comment]
Huh....

Now I guess the question would be enough is that hitting the catch on your system...

@FriedrichWeinmann

**Comment by peedeeboy** [comment]
So I FINALLY got to the actual bottom of the 4100.  It is this bug in PS, that is fixed in PSCore 7:
https://github.com/PowerShell/PowerShell/issues/9185

I thought at first that it was the exception I quoted earlier, which is caused by the `.Matches[1]` call, when no flie has been found (i.e. no error log / message log has been created yet).  I assumed that even though the empty `catch{ }` block throws the exception away, it must be bubbling up to the Windows Event Viewer as a 4100.

Nope.

It is `Select-Object -First 1 -ExpandProperty Name`, which doesn't throw an exception per se (so it doesn't get caught by the `catch { }` block), but is somehow using exceptions in a non-standard way under the hood... and does bubble up to the Event Viewer

From my testing, adding the `-Wait` parameter to `Select-Object` seems to prevent the 4100, so the code could be refactored as:
```powershell
try { [int]$num_Error = (Get-ChildItem -Path $root.FullName -Filter "dbatools_$($pid)_error_*.xml" | Sort-Object LastWriteTime -Descending | Select-Object -First 1 -Wait -ExpandProperty Name | Select-String -Pattern "(\d+)" -AllMatches).Matches[1].Value }
catch { }
```

or alternatively, to prevent the `Cannot index into a null array.` exception as well, something like:
```powershell
$errorfiles =  Get-ChildItem -Path $root.FullName -Filter "dbatools_$($pid)_error_*.xml" | Sort-Object LastWriteTime -Descending
            [int]$num_Error = if ($errorfiles) {(Select-String -InputObject $errorfiles[0].Name -Pattern "(\d+)" -AllMatches).Matches[1].Value} else {0}
```

Any preference of the above two approaches?  I'd be happy to throw a PR together...

**Comment by andreasjordan** [comment]
@peedeeboy Sorry, has been lost from sight. Is this still a problem? If you like to open a PR, please do so. I don't know which of the two approaches is better, maybe @FriedrichWeinmann can have a look and choose.

**Comment by wsmelton** [comment]
There has been no fix applied to our logging system to resolve this to date that I'm aware of. The issue still exists and is constant if you leave a Windows PowerShell session open.

![image](https://user-images.githubusercontent.com/11204251/120874628-2e127200-c56d-11eb-8f27-cd782c6a9c0c.png)

```console
TimeCreated  : 6/4/2021 7:43:10 PM                                       
ProviderName : Microsoft-Windows-PowerShell                              
Id           : 4100                                                      
Message      : Error Message = System error.                             
                                                                         
                                                                         
               Context:                                                  
                       Severity = Warning                                
                       Host Name = Default Host                          
                       Host Version = 5.1.19041.906                      
                       Host ID = d4af7ea3-0a62-4400-a90c-d43b914217fb    
                       Host Application = powershell.exe                 
                       Engine Version = 5.1.19041.906                    
                       Runspace ID = e61bfb89-c0bb-475a-ba94-97027af0f6f0
                       Pipeline ID = 1                                   
                       Command Name =                                    
                       Command Type =                                    
                       Script Name =                                     
                       Command Path =                                    
                       Sequence Number = 5374                            
                       User = THYCOTIC\SMelton                           
                       Connected User =                                  
                       Shell ID = Microsoft.PowerShell                   
                                                                         
                                                                         
               User Data:                                                ```

**Comment by andreasjordan** [comment]
Hi Shawn, thanks for showing the behavior. 
So the questions is: How can we technically solve this? Who has the time and the knowledge to work on this?

**Comment by wsmelton** [comment]
No clue but we can't close issues just because no one can work on it.

**Comment by andreasjordan** [comment]
I agree. But having old bug reports that have not been worked on for months is not a good reputation for a project. We should provide escalation rounds for such cases to find an expert for these issues.

**Comment by andreasjordan** [comment]
Maybe label all these as "hard-fix" and have a look at them all together the the "senior" contributors?

**Comment by wsmelton** [comment]
> But having old bug reports that have not been worked on for months is not a good reputation for a project

Hold up, the reputation of a project can never be determined by the issue count on GitHub. We are an open-sourced project, not a product company. If folks are judging based on that all I can tell them is "they are doing it wrong" 😉.

> We should provide escalation rounds for such cases to find an expert for these issues.

In some areas that is the author, but contributors come and go based on availability (and interest). Many that started on this project are not available as much anymore, we can't hold that against them. We all have various projects or responsibilities that take precedence as time comes and goes; some of these issues are going to be "we get to it when we get to it".

**Comment by potatoqualitee** [comment]
Thanks everyone for working on this! I agree with Shawn in that some issues should be able to be left open, even if we don't have the current expertise or time to address it. My hope is that people judge the project by its usefulness and not by an issue count.

At the same time, I looooooooooove when the number of issues is reduced and I think a low issue count is an incredible goal to work towards.

I'll ping Fred in the PS Slack and ask if he can take a look, as this likely impacts his PSFramework as well. This is out of the bounds of my own expertise.

**Comment by andreasjordan** [comment]
@peedeeboy : Thanks for your work on this, https://github.com/sqlcollaborative/dbatools/issues/6543#issuecomment-633255928 seems to solve the problem. As you see in the linked pull request, I mainly followed your second approach.

Sorry for not trying this earlier.
